"$schema" = "node_modules/wrangler/config-schema.json"
name = "crdb"
main = ".output/server/index.mjs"
compatibility_date = "2025-07-29"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = ".output/public"

[observability]
enabled = true

[[ d1_databases ]]
binding = "crdb_db"
database_name = "crdb"
database_id = "todo"
migrations_dir = "drizzle"